
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/denis/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.14.0-63.fc42.x86_64 - x86_64
...
